package com.dzen.campfire.api

import com.dzen.campfire.api.models.AchievementInfo
import com.dzen.campfire.api.models.Language
import com.dzen.campfire.api.models.Link
import com.dzen.campfire.api.models.QuestInfo
import com.dzen.campfire.api.models.lvl.LvlInfoAdmin
import com.dzen.campfire.api.models.lvl.LvlInfoModeration
import com.dzen.campfire.api.models.lvl.LvlInfoUser
import com.dzen.campfire.api.models.project.StoryQuest
import com.dzen.campfire.api.tools.client.ApiClient
import com.dzen.campfire.api.tools.client.TokenProvider
import com.sup.dev.java.tools.ToolsText

class API(
        projectKey: String,
        tokenProvider: TokenProvider,
        host: String,
        portHttps: Int,
        portCertificate: Int,
        saver: (String, String?) -> Unit,
        loader: (String) -> String?
) : ApiClient(projectKey, tokenProvider, host, portHttps, portCertificate, saver, loader) {

    companion object {

        val PORT_HTTPS = 4026
        val PORT_HTTP = 4028
        val PORT_CERTIFICATE = 4027
        val PORT_STREAM = 4200
        val IP = "46.254.16.245"
        val DOMEN = "http://campfiresayzen.net/r/r.php?a="
        val DOMEN_OLD = "http://sayzen.ru/r/r.php?a="
        val VERSION = "1.285"
        val SUPPORTED_VERSION = "0.82b"

        val PROJECT_KEY_CAMPFIRE = "Campfire"
        val PROJECT_KEY_CAMPFIRE_FORTNITE = "Campfire-Fortnite"
        val PROJECT_KEY_CAMPFIRE_TERRARIA = "Campfire-Terraria"
        val PROJECT_KEY_CAMPFIRE_PUBG = "Campfire-Pubg"
        val PROJECT_KEY_CAMPFIRE_ANIME = "Campfire-Anime"

        val PROTOADMINS = arrayOf(1L)

        val LINK_BOX_WITH_FIREWORKS = Link("box_with_fireworks", true)
        val LINK_BOX_WITH_SUMMER = Link("box_with_summer", true)
        val LINK_BOX_WITH_AUTUMN = Link("box_with_autumn", true)
        val LINK_BOX_WITH_WINTER = Link("box_with_winter", true)
        val LINK_BOX_WITH_CRASH = Link("box_with_crash", true)
        val LINK_BOX_WITH_BOMB = Link("box_with_bomb", true)
        val LINK_BOX_WITH_SNOW = Link("box_with_snow", true)
        val LINK_BOX_WITH_MINIGAME = Link("box_with_minigame", true)
        val LINK_BOX_WITH_BOX = Link("box_with_box", true)
        val LINK_BOX_WITH_MAGIC = Link("box_with_magic", true)
        val LINK_BOX_WITH_MAGIC_SCREEN = Link("screen_with_magic", true)
        val LINK_BOX_WITH_MAGIC_X2 = Link("box_with_magic_x2", true)
        val LINK_BOX_WITH_MAGIC_SCREEN_X2 = Link("screen_with_magic_x2", true)
        val LINK_BOX_WITH_GOOSE = Link("box_with_goose", true)
        val LINK_BOX_WITH_CONFETTI = Link("box_with_confetti", true)
        val LINK_RULES_USER = Link("app_rules", true)
        val LINK_RULES_MODER = Link("app_rules_moderator", true)
        val LINK_RULES_GALLERY = Link("app_gallery", true)
        val LINK_TRANSLATES= Link("app_translates", true)
        val LINK_CREATORS = Link("app_creators", true)
        val LINK_ABOUT = Link("app_about", true)
        val LINK_DONATE = Link("app_donate", true)
        val LINK_DONATE_MAKE = Link("app_donateMake", true)
        val LINK_POST = Link("post")
        val LINK_CHAT = Link("chat")
        val LINK_CONF = Link("conf")
        val LINK_FANDOM = Link("fandom")
        val LINK_PROFILE_ID = Link("profile_id")
        val LINK_MODERATION = Link("moderation")
        val LINK_STICKER = Link("sticker")
        val LINK_STICKERS_PACK = Link("stickers")
        val LINK_EVENT = Link("event")
        val LINK_TAG = Link("tag")
        val LINK_WIKI_FANDOM = Link("wikifandom")
        val LINK_WIKI_SECTION = Link("wikisection")
        val LINK_WIKI_ARTICLE = Link("wikiarticle")
        val LINK_RUBRIC = Link("rubric")
        val LINK_FANDOM_CHAT = Link("fandomchat")
        val LINK_ACTIVITY = Link("activity")

        val LINKS_ARRAY = arrayOf(
                LINK_POST,
                LINK_CHAT,
                LINK_CONF,
                LINK_FANDOM,
                LINK_PROFILE_ID,
                LINK_MODERATION,
                LINK_STICKER,
                LINK_STICKERS_PACK,
                LINK_EVENT,
                LINK_TAG,
                LINK_WIKI_FANDOM,
                LINK_WIKI_SECTION,
                LINK_WIKI_ARTICLE,
                LINK_RUBRIC,
                LINK_FANDOM_CHAT,
                LINK_ACTIVITY,
                LINK_BOX_WITH_FIREWORKS,
                LINK_BOX_WITH_SUMMER,
                LINK_BOX_WITH_AUTUMN,
                LINK_BOX_WITH_WINTER,
                LINK_BOX_WITH_CRASH,
                LINK_BOX_WITH_BOMB,
                LINK_BOX_WITH_SNOW,
                LINK_BOX_WITH_MINIGAME,
                LINK_BOX_WITH_BOX,
                LINK_BOX_WITH_MAGIC,
                LINK_BOX_WITH_MAGIC_SCREEN,
                LINK_BOX_WITH_MAGIC_X2,
                LINK_BOX_WITH_MAGIC_SCREEN_X2,
                LINK_BOX_WITH_GOOSE,
                LINK_BOX_WITH_CONFETTI,
                LINK_RULES_USER,
                LINK_TRANSLATES,
                LINK_RULES_MODER,
                LINK_RULES_GALLERY,
                LINK_CREATORS,
                LINK_ABOUT,
                LINK_DONATE,
                LINK_DONATE_MAKE
        )

        val LINK_TAG_PROFILE_NAME = "profile"
        val LINK_SHORT_PROFILE = "@"
        val LINK_SHORT_PROFILE_SECOND = "#"
        val LINK_PROFILE_NAME = "$DOMEN$LINK_TAG_PROFILE_NAME-"

        val ERROR_GONE = "ERROR_GONE"
        val ERROR_BAD_COMMENT = "ERROR_BAD_COMMENT"
        val ERROR_ACCOUNT_IS_BANED = "ERROR_ACCOUNT_IS_BANED"
        val ERROR_ACCESS = "ERROR_ACCESS"
        val ERROR_ALREADY = "ERROR_ALREADY"

        val ERROR_RELAY_NEXT_BANED = "ERROR_RELAY_NEXT_BANED"
        val ERROR_RELAY_NEXT_ALREADY = "ERROR_RELAY_NEXT_ALREADY"
        val ERROR_RELAY_NEXT_REJECTED = "ERROR_RELAY_NEXT_REJECTED"
        val ERROR_RELAY_NEXT_NOT_ALLOWED = "ERROR_RELAY_NEXT_NOT_ALLOWED"

        val ENGLISH = ToolsText.LATIS_S + ToolsText.LATIS_S.toUpperCase() + ToolsText.NUMBERS_S + ToolsText.TEXT_CHARS_s + ToolsText.SPEC

        val LOGIN_SPLITTER= " - "
        val LOGIN_EMAIL_PREFIX = "Email"

        val ACCOUNT_IMG_SIDE = 256
        val ACCOUNT_IMG_SIDE_GIF = 64
        val ACCOUNT_IMG_WEIGHT = 1024 * 16
        val ACCOUNT_IMG_WEIGHT_GIF = 1024 * 128
        val ACCOUNT_TITLE_IMG_W = 800
        val ACCOUNT_TITLE_IMG_H = 400
        val ACCOUNT_TITLE_IMG_GIF_W = 400
        val ACCOUNT_TITLE_IMG_GIF_H = 200
        val ACCOUNT_TITLE_IMG_WEIGHT = 1024 * 32
        val ACCOUNT_TITLE_IMG_GIF_WEIGHT = 1024 * 1024
        val ACCOUNT_NAME_L_MIN = 3
        val ACCOUNT_NAME_L_MAX = 25
        val ACCOUNT_PASSOWRD_L_MIN = 6
        val ACCOUNT_STATUS_MAX_L = 80
        val ACCOUNT_LOGIN_CHARS = ToolsText.LATIS_S + ToolsText.NUMBERS_S
        val ACCOUNT_AGE_MAX = 200
        val ACCOUNT_DESCRIPTION_MAX_L = 1000
        val ACCOUNT_LINK_TITLE_MAX_L = 30
        val ACCOUNT_LINK_URL_MAX_L = 500
        val ACCOUNT_LINK_MAX = 7
        val ACCOUNT_NOTE_MAX = 200

        val FANDOM_TITLE_IMG_W = 800
        val FANDOM_TITLE_IMG_H = 400
        val FANDOM_TITLE_IMG_WEIGHT = 1024 * 32
        val FANDOM_TITLE_IMG_GIF_W = 400
        val FANDOM_TITLE_IMG_GIF_H = 200
        val FANDOM_TITLE_IMG_GIF_WEIGHT = 1024 * 1024
        val FANDOM_IMG_SIDE = 256
        val FANDOM_NAME_CHARS =  ENGLISH
        val FANDOM_IMG_WEIGHT = 1024 * 16
        val CHAT_IMG_BACKGROUND_W = 360
        val CHAT_IMG_BACKGROUND_H = 640
        val CHAT_IMG_BACKGROUND_WEIGHT = 1024 * 32
        val FANDOM_NAME_MAX = 100
        val FANDOM_GALLERY_MAX_SIDE = 1024
        val FANDOM_GALLERY_MAX_WEIGHT = 1024 * 32
        val FANDOM_DESCRIPTION_MAX_L = 500
        val FANDOM_GALLERY_MAX = 10
        val FANDOM_LINKS_URL_MAX_L = 500
        val FANDOM_LINKS_TITLE_MAX_L = 30
        val FANDOM_LINKS_MAX = 10
        val FANDOM_NAMES_MAX_L = 20
        val FANDOM_NAMES_MAX = 10
        val FANDOM_KARMA_COF_MIN = 1
        val FANDOM_KARMA_COF_MAX = 300

        val RESOURCES_PUBLICATION_NONE = 0L
        val RESOURCES_PUBLICATION_DATABASE_LINKED = -1L
        val RESOURCES_PUBLICATION_CHAT_MESSAGE = -2L
        val RESOURCES_PUBLICATION_COMMENT = -3L
        val RESOURCES_PUBLICATION_FANDOM_GALLERY = -4L
        val RESOURCES_PUBLICATION_STICKER = -5L
        val RESOURCES_PUBLICATION_STICKER_PACK = -6L
        val RESOURCES_PUBLICATION_TAG = -7L
        val RESOURCES_PUBLICATION_WIKI = -8L
        val RESOURCES_PUBLICATION_ERROR = -100L

        val EFFECT_TAG_SOURCE_SYSTEM = 1L
        val EFFECT_COMMENT_TAG_GODS = 1L
        val EFFECT_COMMENT_TAG_REJECTED = 2L
        val EFFECT_COMMENT_TAG_TOO_MANY = 3L
        val EFFECT_INDEX_HATE = 1L
        val EFFECT_INDEX_PIG = 2L
        val EFFECT_INDEX_VAHTER = 3L
        val EFFECT_INDEX_GOOSE = 4L
        val EFFECT_INDEX_SNOW = 5L
        val EFFECT_INDEX_ADMIN_BAN = 6L
        val EFFECT_INDEX_TRANSLATOR = 7L
        val EFFECT_INDEX_MENTION_LOCK = 8L

        val CHAT_IMG_SIDE = 256
        val CHAT_IMG_SIDE_GIF = 64
        val CHAT_IMG_WEIGHT = 1024 * 16
        val CHAT_IMG_WEIGHT_GIF = 1024 * 16
        val CHAT_NAME_MIN = 1
        val CHAT_NAME_MAX = 100

        val WIKI_NAME_MAX = 200
        val WIKI_IMG_SIDE = 256
        val WIKI_IMG_SIDE_GIF = 64
        val WIKI_IMG_WEIGHT = 1024 * 16
        val WIKI_IMG_WEIGHT_GIF = 1024 * 128
        val WIKI_TITLE_IMG_W = 800
        val WIKI_TITLE_IMG_H = 400
        val WIKI_TITLE_IMG_GIF_W = 400
        val WIKI_TITLE_IMG_GIF_H = 200
        val WIKI_TITLE_IMG_WEIGHT = 1024 * 32
        val WIKI_TITLE_IMG_GIF_WEIGHT = 1024 * 1024
        val WIKI_TYPE_SECION = 1L
        val WIKI_TYPE_ARTICLE = 2L
        val WIKI_PAGES_EVENT_TYPE_PUT = 1L
        val WIKI_PAGES_EVENT_TYPE_REMOVE = 2L
        val WIKI_PAGES_EVENT_TYPE_CHANGE = 3L
        val WIKI_PAGES_EVENT_TYPE_MOVE = 4L
        val WIKI_PAGES_EVENT_TYPE_CHANGE_LANGUAGE = 5L

        val MODERATION_COMMENT_MIN_L = 1
        val MODERATION_COMMENT_MAX_L = 1000

        val LVL_APP_ACCESS = LvlInfoUser(100L, 0L)
        val LVL_CAN_CHANGE_PROFILE_IMAGE = LvlInfoUser(150L, 0L)
        val LVL_CAN_CHANGE_STATUS = LvlInfoUser(175L, 0L)
        val LVL_CAN_MENTION = LvlInfoUser(200L, 0L)
        val LVL_CAN_CHANGE_AVATAR_GIF = LvlInfoUser(250L, 0L)
        val LVL_CAN_PIN_POST = LvlInfoUser(260L, 0L)
        val LVL_CREATE_STICKERS = LvlInfoUser(300L, 0L)
        //  Moderator
        val LVL_MODERATOR_BLOCK = LvlInfoModeration(400L, 300)
        val LVL_MODERATOR_TO_DRAFTS = LvlInfoModeration(410L, 320)
        val LVL_MODERATOR_CHATS = LvlInfoModeration(415L, 325)
        val LVL_MODERATOR_POST_TAGS = LvlInfoModeration(420L, 330)
        val LVL_MODERATOR_FANDOM_IMAGE = LvlInfoModeration(425L, 350)
        val LVL_CAN_CHANGE_PROFILE_IMAGE_GIF = LvlInfoUser(450L, 0L)
        val LVL_MODERATOR_DESCRIPTION = LvlInfoModeration(475L, 400)
        val LVL_MODERATOR_NAMES = LvlInfoModeration(490L, 440)
        val LVL_MODERATOR_WIKI_EDIT = LvlInfoModeration(500L, 400)
        val LVL_ANONYMOUS = LvlInfoUser(505L, 0L)
        val LVL_MODERATOR_GALLERY = LvlInfoModeration(510L, 450)
        val LVL_MODERATOR_TRANSLATE = LvlInfoAdmin(515L, 470)
        val LVL_MODERATOR_LINKS = LvlInfoModeration(520L, 475)
        val LVL_MODERATOR_TAGS = LvlInfoModeration(530L, 500)
        val LVL_MODERATOR_BACKGROUND_IMAGE = LvlInfoModeration(540L, 540)
        val LVL_MODERATOR_PIN_POST = LvlInfoModeration(560L, 550)
        val LVL_MODERATOR_IMPORTANT = LvlInfoModeration(575L, 560)
        val LVL_MODERATOR_CLOSE_POST = LvlInfoModeration(600L, 650)
        val LVL_MODERATOR_RELAY_RACE = LvlInfoModeration(620L, 700)
        val LVL_MODERATOR_RUBRIC = LvlInfoModeration(650L, 800)
        //  Admin
        val LVL_ADMIN_MODER = LvlInfoAdmin(700L, 700)
        val LVL_ADMIN_FANDOM_NAME = LvlInfoAdmin(725L, 900)
        val LVL_ADMIN_FANDOM_AVATAR = LvlInfoAdmin(730L, 950)
        val LVL_ADMIN_FANDOM_PARAMS = LvlInfoAdmin(750L, 1000)
        val LVL_ADMIN_FANDOM_CATEGORY = LvlInfoAdmin(790L, 1080)
        val LVL_ADMIN_BAN = LvlInfoAdmin(800L, 1100)
        val LVL_ADMIN_POST_CHANGE_FANDOM = LvlInfoAdmin(820L, 1150)
        val LVL_ADMIN_MOVE_RUBRIC = LvlInfoAdmin(830L, 1150)
        val LVL_ADMIN_FANDOMS_ACCEPT = LvlInfoAdmin(850L, 1200)
        val LVL_ADMIN_USER_REMOVE_STATUS = LvlInfoAdmin(875L, 1230)
        val LVL_ADMIN_USER_REMOVE_IMAGE = LvlInfoAdmin(880L, 1250)
        val LVL_ADMIN_USER_REMOVE_NAME = LvlInfoAdmin(885L, 1300)
        val LVL_ADMIN_USER_REMOVE_DESCRIPTION = LvlInfoAdmin(888L, 1350)
        val LVL_ADMIN_USER_REMOVE_LINK = LvlInfoAdmin(890L, 1400)
        val LVL_ADMIN_USER_CHANGE_NAME = LvlInfoAdmin(895L, 1410)
        val LVL_ADMIN_USER_PUNISHMENTS_REMOVE = LvlInfoAdmin(900L, 1420)
        val LVL_ADMIN_REMOVE_MODERATOR = LvlInfoAdmin(910L, 1450)
        val LVL_ADMIN_MAKE_MODERATOR = LvlInfoAdmin(925L, 1500)
        val LVL_ADMIN_FANDOM_CLOSE = LvlInfoAdmin(940L, 1550)
        val LVL_ADMIN_TRANSLATE_MODERATOR = LvlInfoAdmin(945L, 1600)
        val LVL_ADMIN_FANDOM_REMOVE = LvlInfoAdmin(950L, 1600)
        val LVL_ADMIN_FANDOM_VICEROY = LvlInfoAdmin(980L, 1650)
        val LVL_ADMIN_FANDOM_ADMIN = LvlInfoAdmin(1000L, 1700)
        val LVL_ADMIN_FANDOM_EFFECTS = LvlInfoAdmin(1050L, 1800)
        val LVL_ADMIN_FANDOM_SET_COF = LvlInfoAdmin(1100L, 2000)
        val LVL_ADMIN_REMOVE_MEDIA = LvlInfoAdmin(1500L, 2000)
        val LVL_ADMIN_DEBUG_RECOUNT_LEVEL_AND_KARMA = LvlInfoAdmin(1200L, 2100)
        //  Protoadmin
        val LVL_PROTOADMIN = LvlInfoAdmin(5000L, 100000L)


        val KARMA_CHANGE_CALLDOWN = (1000 * 60 * 60 * 24).toLong()
        val KARMA_CATEGORY_ABYSS = 0L
        val KARMA_CATEGORY_GOOD = 1L
        val KARMA_CATEGORY_BEST = 2L

        val FANDOM_CAMPFIRE_ID = 10L
        val FANDOM_CAMPFIRE_ANYTHING_ID = 1627L
        val FANDOM_CAMPFIRE_GAMES_ID = 992L
        val FANDOM_CAMPFIRE_ANIME_ID = 993L
        val FANDOM_CAMPFIRE_MUSIC_ID = 1209L
        val FANDOM_CAMPFIRE_PROGRAMS_ID = 0L
        val FANDOM_CAMPFIRE_MOVIEWS_ID = 0L
        val FANDOM_CAMPFIRE_OTHER_ID = 0L
        val FANDOM_CAMPFIRE_SITES_ID = 0L
        val FANDOM_CAMPFIRE_ORGANIZATIONS_ID = 0L
        val FANDOM_CAMPFIRE_EVENTS_ID = 0L
        val FANDOM_CAMPFIRE_HELLO_ID = 2776L
        val FANDOM_CAMPFIRE_FORTNITE_ID = 7L
        val FANDOM_CAMPFIRE_TERRARIA_ID = 6L
        val FANDOM_CAMPFIRE_PUBG_ID = 70L
        val FANDOM_CAMPFIRE_ANIME = 993L
        val FANDOM_CHAT_TEXT_MIN_L = 1
        val FANDOM_CHAT_TEXT_MAX_L = 5000

        val ACHI_APP_SHARE = AchievementInfo(2, 5, 1)
        val ACHI_CONTENT_SHARE = AchievementInfo(3, 5, 1, 10, 30)
        val ACHI_ADD_RECRUITER = AchievementInfo(4, 10, 1)
        val ACHI_ENTERS = AchievementInfo(5, 5, *IntArray(500) { (it + 1) * 5 })
        val ACHI_KARMA_COUNT = AchievementInfo(6, 5, *IntArray(20) { (it + 1) * 20000 })
        val ACHI_REFERRALS_COUNT = AchievementInfo(7, 10, 3, 12, 36)
        val ACHI_RATES_COUNT = AchievementInfo(8, 5, 100)
        val ACHI_COMMENTS_KARMA = AchievementInfo(12, 10, 5000, 25000, 50000)
        val ACHI_POSTS_COUNT = AchievementInfo(15, 5, 10, 50, 200)
        val ACHI_COMMENTS_COUNT = AchievementInfo(16, 5, 100)
        val ACHI_LOGIN = AchievementInfo(28, 5, 1)
        val ACHI_CHAT = AchievementInfo(29, 5, 1)
        val ACHI_COMMENT = AchievementInfo(30, 5, 1)
        val ACHI_ANSWER = AchievementInfo(31, 5, 1)
        val ACHI_RATE = AchievementInfo(32, 5, 1)
        val ACHI_CHANGE_PUBLICATION = AchievementInfo(33, 5, 1)
        val ACHI_CHANGE_COMMENT = AchievementInfo(34, 5, 1)
        val ACHI_POST_KARMA = AchievementInfo(36, 10, 10000, 50000, 100000)
        val ACHI_FIRST_POST = AchievementInfo(37, 5, 1)
        val ACHI_SUBSCRIBE = AchievementInfo(38, 5, 1)
        val ACHI_TAGS_SEARCH = AchievementInfo(39, 5, 1)
        val ACHI_LANGUAGE = AchievementInfo(40, 5, 1)
        val ACHI_TITLE_IMAGE = AchievementInfo(41, 5, 1)
        val ACHI_CREATE_TAG = AchievementInfo(42, 5, 1)
        val ACHI_QUESTS = AchievementInfo(43, 2, *IntArray(500) { it + 1 })
        val ACHI_FANDOMS = AchievementInfo(44, 10, 1, 3, 5, 10, 20)
        val ACHI_RULES_USER = AchievementInfo(45, 5, 1)
        val ACHI_RULES_MODERATOR = AchievementInfo(46, 5, 1)
        val ACHI_FOLLOWERS = AchievementInfo(47, 5, 10, 100, 250, 500, 1000, 5000, 10000)
        val ACHI_MODER_CHANGE_POST_TAGS = AchievementInfo(48, 5, 1)
        val ACHI_FIREWORKS = AchievementInfo(50, 1, 1)
        val ACHI_MAKE_MODER = AchievementInfo(51, 5, 1)
        val ACHI_CREATE_CHAT = AchievementInfo(52, 5, 1)
        val ACHI_REVIEW_MODER_ACTION = AchievementInfo(53, 5, 1)
        val ACHI_ACCEPT_FANDOM = AchievementInfo(54, 5, 1)
        val ACHI_MODERATOR_COUNT = AchievementInfo(55, 5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        val ACHI_MODERATOR_ACTION_KARMA = AchievementInfo(56, 5, 5000, 10000, 20000, 50000, 100000)
        val ACHI_KARMA_30 = AchievementInfo(57, 5, 50000, 100000, 200000, 400000, 800000, 1500000, 3000000)
        val ACHI_UP_RATES = AchievementInfo(58, 2, 10, 50, 150, 300, 500)
        val ACHI_UP_RATES_OVER_DOWN = AchievementInfo(59, 2, 5, 20, 50, 150, 300, 500)
        val ACHI_CHAT_SUBSCRIBE = AchievementInfo(60, 2, 1)
        val ACHI_STICKERS_KARMA = AchievementInfo(61, 10, 5000, 25000, 50000)
        val ACHI_UNKNOWN = AchievementInfo(62, 0, 0)
        val ACHI_RELAY_RACE_FIRST_POST = AchievementInfo(64, 1, 1)
        val ACHI_RELAY_RACE_FIRST_NEXT_MEMBER = AchievementInfo(65, 1, 1)
        val ACHI_RELAY_RACE_FIRST_CREATE = AchievementInfo(66, 1, 1)
        val ACHI_RELAY_RACE_POSTS_COUNT = AchievementInfo(67, 5, 5, 10, 20, 50)
        val ACHI_RELAY_RACE_MY_RACE_POSTS_COUNT = AchievementInfo(68, 5, 5, 10, 20, 50, 100)
        val ACHI_VICEROY_ASSIGN = AchievementInfo(69, 1, 1)
        val ACHI_VICEROY_POSTS_COUNT = AchievementInfo(70, 2, 5, 10, 20, 50)
        val ACHI_VICEROY_WIKI_COUNT = AchievementInfo(71, 2, 1, 5, 10, 50, 100)
        val ACHI_VICEROY_KARMA_COUNT = AchievementInfo(72, 2, 50000, 200000, 500000, 1000000)
        val ACHI_VICEROY_SUBSCRIBERS_COUNT = AchievementInfo(73, 2, 10, 20, 50, 100, 500)
        val ACHI_VICEROY_LINK = AchievementInfo(74, 1, 1)
        val ACHI_VICEROY_IMAGES = AchievementInfo(75, 1, 1)
        val ACHI_VICEROY_DESCRIPTION = AchievementInfo(76, 1, 1)

        val ACHI_PACK_1 = arrayOf(ACHI_RULES_USER, ACHI_LOGIN, ACHI_CHAT, ACHI_CHAT_SUBSCRIBE, ACHI_COMMENT, ACHI_ANSWER, ACHI_RATE, ACHI_CHANGE_PUBLICATION, ACHI_CHANGE_COMMENT, ACHI_FIRST_POST, ACHI_SUBSCRIBE, ACHI_TAGS_SEARCH, ACHI_LANGUAGE, ACHI_TITLE_IMAGE, ACHI_RELAY_RACE_FIRST_POST, ACHI_RELAY_RACE_FIRST_NEXT_MEMBER)
        val ACHI_PACK_2 = arrayOf(ACHI_APP_SHARE, ACHI_CONTENT_SHARE, ACHI_ADD_RECRUITER, ACHI_REFERRALS_COUNT, ACHI_FOLLOWERS)
        val ACHI_PACK_3 = arrayOf(ACHI_POSTS_COUNT, ACHI_COMMENTS_COUNT, ACHI_POST_KARMA, ACHI_COMMENTS_KARMA, ACHI_STICKERS_KARMA, ACHI_KARMA_COUNT, ACHI_KARMA_30, ACHI_UP_RATES, ACHI_UP_RATES_OVER_DOWN, ACHI_RELAY_RACE_POSTS_COUNT, ACHI_RELAY_RACE_MY_RACE_POSTS_COUNT)
        val ACHI_PACK_4 = arrayOf(ACHI_CREATE_TAG, ACHI_RULES_MODERATOR, ACHI_MODER_CHANGE_POST_TAGS, ACHI_MAKE_MODER, ACHI_CREATE_CHAT, ACHI_REVIEW_MODER_ACTION, ACHI_ACCEPT_FANDOM, ACHI_MODERATOR_COUNT, ACHI_MODERATOR_ACTION_KARMA, ACHI_RELAY_RACE_FIRST_CREATE)
        val ACHI_PACK_5 = arrayOf(ACHI_RATES_COUNT, ACHI_ENTERS, ACHI_QUESTS, ACHI_FANDOMS, ACHI_FIREWORKS)
        val ACHI_PACK_6 = arrayOf(ACHI_VICEROY_ASSIGN, ACHI_VICEROY_POSTS_COUNT, ACHI_VICEROY_WIKI_COUNT, ACHI_VICEROY_KARMA_COUNT, ACHI_VICEROY_SUBSCRIBERS_COUNT, ACHI_VICEROY_LINK, ACHI_VICEROY_IMAGES, ACHI_VICEROY_DESCRIPTION)

        val DONATE_COMMENT_MAX_L = 300

        val QUEST_POSTS = QuestInfo(1, false, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6)
        val QUEST_POST_KARMA = QuestInfo(2, false, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120)
        val QUEST_COMMENTS = QuestInfo(3, false, 2, 5, 8, 12, 16, 20, 24, 28, 30)
        val QUEST_COMMENTS_KARMA = QuestInfo(4, false, 2, 5, 8, 12, 16, 20, 24, 28, 30)
        val QUEST_CHAT = QuestInfo(5, false, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70)
        val QUEST_RATES = QuestInfo(6, false, 6, 12, 18, 24, 28, 32, 36, 40, 48, 52, 58, 64)
        val QUEST_KARMA = QuestInfo(7, false, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120)
        val QUEST_UNKNOWN = QuestInfo(8, false, 0)
        val QUEST_ACTIVITIES = QuestInfo(9, false, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2)

        val QUEST_STORY_START = StoryQuest(0)
        val QUEST_STORY_KARMA = StoryQuest(3)
        val QUEST_STORY_ACHI_SCREEN = StoryQuest(1)
        val QUEST_STORY_CHAT = StoryQuest(5)
        val QUEST_STORY_FANDOM = StoryQuest(1)
        val QUEST_STORY_PROFILE = StoryQuest(1)
        val QUEST_STORY_COMMENTS = StoryQuest(5)
        val QUEST_STORY_FILTERS = StoryQuest(1)
        val QUEST_STORY_BOOKMARKS = StoryQuest(1)
        val QUEST_STORY_BOOKMARKS_SCREEN = StoryQuest(1)
        val QUEST_STORY_DRAFT = StoryQuest(3L)
        val QUEST_STORY_RATINGS = StoryQuest(1)
        val QUEST_STORY_STICKERS = StoryQuest(1)
        val QUEST_STORY_POST = StoryQuest(1)
        val QUEST_STORY_FINISH = StoryQuest(0)
        val QUEST_STORY_FUTURE = StoryQuest(1)

        val QUEST_STORY_ORDER_ARRAY = arrayOf(
                QUEST_STORY_START,
                QUEST_STORY_KARMA,
                QUEST_STORY_ACHI_SCREEN,
                QUEST_STORY_CHAT,
                QUEST_STORY_FANDOM,
                QUEST_STORY_PROFILE,
                QUEST_STORY_COMMENTS,
                QUEST_STORY_FILTERS,
                QUEST_STORY_BOOKMARKS,
                QUEST_STORY_BOOKMARKS_SCREEN,
                QUEST_STORY_DRAFT,
                QUEST_STORY_RATINGS,
                QUEST_STORY_STICKERS,
                QUEST_STORY_POST,
                QUEST_STORY_FINISH,
                QUEST_STORY_FUTURE
        )

        init {
            for (i in QUEST_STORY_ORDER_ARRAY.indices) QUEST_STORY_ORDER_ARRAY[i].index = i
        }

        val CATEGORY_GAMES = 1L
        val CATEGORY_ANIME = 2L
        val CATEGORY_MUSIC = 3L
        val CATEGORY_PROGRAMS = 4L
        val CATEGORY_MOVIES = 5L
        val CATEGORY_SITE = 6L
        val CATEGORY_COMPANY = 7L
        val CATEGORY_BOOKS = 8L
        val CATEGORY_ANIMALS = 9L
        val CATEGORY_HOBBIES = 10L
        val CATEGORY_PEOPLE = 11L
        val CATEGORY_EVENT = 12L
        val CATEGORY_PLANTS = 13L
        val CATEGORY_PLACES = 14L
        val CATEGORY_OTHER = 100L
        val CATEGORY_UNKNOWN = 101L

        val STATUS_DRAFT = 1L
        val STATUS_PUBLIC = 2L
        val STATUS_BLOCKED = 3L
        val STATUS_DEEP_BLOCKED = 4L
        val STATUS_PENDING = 5L
        val STATUS_ARCHIVE = 6L
        val STATUS_REMOVED = 7L

        val RUBRIC_NAME_MIN = 1
        val RUBRIC_NAME_MAX = 100
        val RUBRIC_COF_MAX = 300L
        val RUBRIC_COF_MIN = 100L
        val RUBRIC_COF_STEP_DOWN = 10L
        val RUBRIC_COF_STEP_UP = 5L
        val RUBRIC_KARMA_BOUND = 10000

        val ACTIVITIES_NAME_MIN = 1
        val ACTIVITIES_NAME_MAX = 100
        val ACTIVITIES_DESC_MIN = 1
        val ACTIVITIES_DESC_MAX = 1000
        val ACTIVITIES_TYPE_RELAY_RACE = 1L
        val ACTIVITIES_RELAY_RACE_TIME = 1000L * 60 * 60 * 24
        val ACTIVITIES_COLLISION_TYPE_RELAY_RACE_POST = 1L
        val ACTIVITIES_COLLISION_TYPE_RELAY_RACE_MEMBER = 2L
        val ACTIVITIES_COLLISION_TYPE_SUBSCRIBE = 3L
        val ACTIVITIES_COLLISION_TYPE_RELAY_RACE_REJECTED = 4L
        val ACTIVITIES_COLLISION_TYPE_RELAY_RACE_LOST= 5L

        val PUBLICATION_TYPE_COMMENT = 1L
        val PUBLICATION_TYPE_CHAT_MESSAGE = 8L
        val PUBLICATION_TYPE_POST = 9L
        val PUBLICATION_TYPE_TAG = 10L
        val PUBLICATION_TYPE_MODERATION = 11L
        val PUBLICATION_TYPE_EVENT_USER = 12L
        val PUBLICATION_TYPE_STICKERS_PACK = 15L
        val PUBLICATION_TYPE_STICKER = 16L
        val PUBLICATION_TYPE_EVENT_MODER = 17L
        val PUBLICATION_TYPE_EVENT_ADMIN = 18L
        val PUBLICATION_TYPE_EVENT_FANDOM = 19L
        val PUBLICATION_TYPE_UNKNOWN = 20L

        val PUBLICATION_IMPORTANT_IMPORTANT = -1L
        val PUBLICATION_IMPORTANT_DEFAULT = 0L
        val PUBLICATION_IMPORTANT_NONE = 1L

        val PAGE_TYPE_TEXT = 1L
        val PAGE_TYPE_IMAGE = 2L
        val PAGE_TYPE_IMAGES = 3L
        val PAGE_TYPE_LINK = 4L
        val PAGE_TYPE_QUOTE = 5L
        val PAGE_TYPE_SPOILER = 6L
        val PAGE_TYPE_POLLING = 7L
        val PAGE_TYPE_VIDEO = 9L
        val PAGE_TYPE_TABLE = 10L
        val PAGE_TYPE_DOWNLOAD = 11L
        val PAGE_TYPE_CAMPFIRE_OBJECT = 12L
        val PAGE_TYPE_USER_ACTIVITY = 13L
        val PAGE_TYPE_LINK_IMAGE = 14L
        val PAGE_TYPE_UNKNOWN = 15L
        val PAGE_TYPE_CODE = 16L

        val MODERATION_TYPE_BLOCK = 1L
        val MODERATION_TYPE_TAG_CREATE = 2L
        val MODERATION_TYPE_TAG_CHANGE = 3L
        val MODERATION_TYPE_TAG_REMOVE = 4L
        val MODERATION_TYPE_DESCRIPTION = 5L
        val MODERATION_TYPE_GALLERY_ADD = 6L
        val MODERATION_TYPE_GELLERY_REMOVE = 7L
        val MODERATION_TYPE_TITLE_IMAGE = 8L
        val MODERATION_TYPE_IMPORTANT = 9L
        val MODERATION_TYPE_LINK_ADD = 10L
        val MODERATION_TYPE_LINK_REMOVE = 11L
        val MODERATION_TYPE_TO_DRAFTS = 12L
        val MODERATION_TYPE_POST_TAGS = 13L
        val MODERATION_TYPE_NAMES = 14L
        val MODERATION_TYPE_FORGIVE = 15L
        val MODERATION_TYPE_BACKGROUND_IMAGE = 16L
        val MODERATION_TYPE_LINK_CHANGE = 17L
        val MODERATION_TYPE_TAG_MOVE = 170L
        val MODERATION_TYPE_TAG_MOVE_BETWEEN_CATEGORY = 171L
        val MODERATION_TYPE_TAG_PIN_POST_IN_FANDOM = 172L
        val MODERATION_TYPE_UNKNOWN = 173L
        val MODERATION_TYPE_MULTILINGUAL_NOT = 174L
        val MODERATION_TYPE_POST_CLSOE = 175L
        val MODERATION_TYPE_POST_CLSOE_NO = 176L
        val MODERATION_TYPE_RUBRIC_CHANGE_NAME = 177L
        val MODERATION_TYPE_RUBRIC_CHANGE_OWNER = 178L
        val MODERATION_TYPE_RUBRIC_CREATE = 179L
        val MODERATION_TYPE_RUBRIC_REMOVE = 180L
        val MODERATION_TYPE_RUBRIC_MOVE_FANDOM = 188L
        val MODERATION_TYPE_CHAT_CREATE = 181L
        val MODERATION_TYPE_CHAT_CHANGE = 182L
        val MODERATION_TYPE_CHAT_REMOVE = 183L
        val MODERATION_TYPE_BACKGROUND_IMAGE_SUB = 184L
        val MODERATION_TYPE_ACTIVITIES_CREATE = 185L
        val MODERATION_TYPE_ACTIVITIES_CHANGE = 186L
        val MODERATION_TYPE_ACTIVITIES_REMOVE = 187L


        val PUBLICATION_EVENT_USER_ACHIEVEMENT = 1L
        val PUBLICATION_EVENT_USER_FANDOM_SUGGEST = 3L
        val PUBLICATION_EVENT_USER_UNKNOWN = 33L
        val PUBLICATION_EVENT_USER_ADMIN_BANED = 34L
        val PUBLICATION_EVENT_USER_ADMIN_WARNED = 35L
        val PUBLICATION_EVENT_USER_ADMIN_NAME_CHANGED = 36L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_PUNISHMENT = 37L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_DESCRIPTION = 38L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_LINK = 39L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_STATUS = 40L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_IMAGE = 41L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_NAME = 42L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_TITLE_IMAGE = 43L
        val PUBLICATION_EVENT_USER_ADMIN_MAKE_MODER = 44L
        val PUBLICATION_EVENT_USER_ADMIN_REMOVE_MODER = 45L
        val PUBLICATION_EVENT_USER_ADMIN_MODERATION_REJECTED = 46L
        val PUBLICATION_EVENT_USER_ADMIN_PUBLICATION_RESTORED = 47L
        val PUBLICATION_EVENT_USER_ADMIN_POST_CHANGE_FANDOM = 50L
        val PUBLICATION_EVENT_USER_ADMIN_PUBLICATION_BLOCKED = 51L
        val PUBLICATION_EVENT_USER_QUEST_FINISH = 52L
        val PUBLICATION_EVENT_USER_ADMIN_VICEROY_ASSIGN = 53L
        val PUBLICATION_EVENT_USER_ADMIN_VICEROY_REMOVE = 54L
        val PUBLICATION_EVENT_USER_EFFECT_ADD = 55L
        val PUBLICATION_EVENT_USER_EFFECT_REMOVE = 56L
        val PUBLICATION_EVENT_USER_TRANSLATE_REJECTED = 57L
        val PUBLICATION_EVENT_USER_ADMIN_POST_REMOVE_MEDIA = 58L
        val PUBLICATION_EVENT_USER_ADMIN_VOTE_CANCELED_FOR_ADMIN = 59L
        val PUBLICATION_EVENT_USER_ADMIN_VOTE_CANCELED_FOR_USER = 60L

        val PUBLICATION_EVENT_ADMIN_USER_CHANGE_NAME = 4L
        val PUBLICATION_EVENT_ADMIN_USER_REMOVE_NAME = 5L
        val PUBLICATION_EVENT_ADMIN_USER_REMOVE_IMAGE = 6L
        val PUBLICATION_EVENT_ADMIN_USER_REMOVE_TITILE_IMAGE = 7L
        val PUBLICATION_EVENT_ADMIN_FANDOM_REMOVE = 8L
        val PUBLICATION_EVENT_ADMIN_FANDOM_CHANGE_AVATAR = 9L
        val PUBLICATION_EVENT_ADMIN_FANDOM_RENAME = 11L
        val PUBLICATION_EVENT_ADMIN_USER_REMOVE_STATUS = 14L
        val PUBLICATION_EVENT_ADMIN_BAN = 15L
        val PUBLICATION_EVENT_ADMIN_USER_REMOVE_DESCRIPTION = 16L
        val PUBLICATION_EVENT_ADMIN_USER_REMOVE_LINK = 17L
        val PUBLICATION_EVENT_ADMIN_FANDOM_CHANGE_PARAMS = 19L
        val PUBLICATION_EVENT_ADMIN_WARN = 21L
        val PUBLICATION_EVENT_ADMIN_FANDOM_MAKE_MODERATOR = 22L
        val PUBLICATION_EVENT_ADMIN_FANDOM_REMOVE_MODERATOR = 23L
        val PUBLICATION_EVENT_ADMIN_PUNISHMENT_REMOVE = 24L
        val PUBLICATION_EVENT_ADMIN_MODERATION_REJECTED = 25L
        val PUBLICATION_EVENT_ADMIN_PUBLICATION_RESTORE = 26L
        val PUBLICATION_EVENT_ADMIN_POST_CHANGE_FANDOM = 27L
        val PUBLICATION_EVENT_ADMIN_FANDOM_CHANGE_CATEGORY = 28L
        val PUBLICATION_EVENT_ADMIN_FANDOM_CLOSE = 29L
        val PUBLICATION_EVENT_ADMIN_FANDOM_COF_CHANGED = 31L
        val PUBLICATION_EVENT_ADMIN_UNKNOWN = 32L
        val PUBLICATION_EVENT_ADMIN_FANDOM_SUGGEST = 200L
        val PUBLICATION_EVENT_ADMIN_BLOCK_PUBLICATION = 201L
        val PUBLICATION_EVENT_ADMIN_FANDOM_VICEROY_ASSIGN = 202L
        val PUBLICATION_EVENT_ADMIN_FANDOM_VICEROY_REMOVE = 203L
        val PUBLICATION_EVENT_ADMIN_TRANSLATE = 204L
        val PUBLICATION_EVENT_ADMIN_EFFECT_ADD = 205L
        val PUBLICATION_EVENT_ADMIN_EFFECT_REMOVE = 206L
        val PUBLICATION_EVENT_ADMIN_TRANSLATE_REJECTED = 207L
        val PUBLICATION_EVENT_ADMIN_POST_REMOVE_MEDIA = 208L
        val PUBLICATION_EVENT_ADMIN_ADMIN_VOTE_CANCELED = 209L

        val ADMIN_VOTE_UNKNOWN = 1L
        val ADMIN_VOTE_ACCOUNT_RECOUNT_ACHI = 2L
        val ADMIN_VOTE_ACCOUNT_CHANGE_NAME = 3L
        val ADMIN_VOTE_ACCOUNT_EFFECT = 4L
        val ADMIN_VOTE_ACCOUNT_PUNISH = 5L
        val ADMIN_VOTE_ACCOUNT_RECOUNT_KARMA = 6L
        val ADMIN_VOTE_ACCOUNT_REMOVE_AVATAR = 7L
        val ADMIN_VOTE_ACCOUNT_REMOVE_BACKGROUND = 8L
        val ADMIN_VOTE_ACCOUNT_REMOVE_NAME = 9L
        val ADMIN_VOTE_ACCOUNT_REMOVE_REPORTS = 10L
        val ADMIN_VOTE_ACCOUNT_REMOVE_STATUS = 11L
        val ADMIN_VOTE_FANDOM_REMOVE = 12L

        val PUBLICATION_EVENT_MODER_UNKNOWN = 30L

        val PUBLICATION_EVENT_FANDOM_UNKNOWN = 100L
        val PUBLICATION_EVENT_FANDOM_ACCEPTED = 101L
        val PUBLICATION_EVENT_FANDOM_CHANGE_CATEGORY = 102L
        val PUBLICATION_EVENT_FANDOM_RENAME = 103L
        val PUBLICATION_EVENT_FANDOM_CHANGE_AVATAR = 104L
        val PUBLICATION_EVENT_FANDOM_CHANGE_PARAMS = 105L
        val PUBLICATION_EVENT_FANDOM_CLOSE = 106L
        val PUBLICATION_EVENT_FANDOM_MAKE_MODERATOR = 107L
        val PUBLICATION_EVENT_FANDOM_REMOVE = 108L
        val PUBLICATION_EVENT_FANDOM_REMOVE_MODERATOR = 109L
        val PUBLICATION_EVENT_FANDOM_KARMA_COF_CHANGED = 110L
        val PUBLICATION_EVENT_FANDOM_VICEROY_ASSIGN = 111L
        val PUBLICATION_EVENT_FANDOM_VICEROY_REMOVE = 112L

        val BOOKMARKS_FOLDERS_NAME_MAX = 50L
        val BOOKMARKS_FOLDERS_MAX = 5L

        val COLLISION_BOOKMARK = 6L
        val COLLISION_SHARE = 9L
        val COLLISION_TAG = 11L
        val COLLISION_KARMA_30 = 14L
        val COLLISION_PAGE_POLLING_VOTE = 21L
        val COLLISION_COMMENTS_WATCH = 24L
        val COLLISION_PUNISHMENTS_WARN = 25L
        val COLLISION_PUNISHMENTS_BAN = 26L
        val COLLISION_ACHIEVEMENT_RULES_USER = 10000L
        val COLLISION_ACHIEVEMENT_RULES_MODER = 10001L
        val COLLISION_ACHIEVEMENT_SHARE_APP = 10002L
        val COLLISION_ACHIEVEMENT_TAG_SEARCH = 10003L
        val COLLISION_ACHIEVEMENT_CHANGE_PUBLICATION = 10004L
        val COLLISION_ACHIEVEMENT_FANDOM_LANGUAGE = 10005L
        val COLLISION_ACHIEVEMENT_TAG_CREATE = 10006L
        val COLLISION_ACHIEVEMENT_CHANGE_COMMENT = 10007L
        val COLLISION_ACHIEVEMENT_COMMENT = 10008L
        val COLLISION_ACHIEVEMENT_ANSWER = 10009L
        val COLLISION_ACHIEVEMENT_MODERATIONS_POST_TAGS = 10010L
        val COLLISION_ACHIEVEMENT_FAERWORKS = 10012L
        val COLLISION_ACHIEVEMENT_MAKE_MODER = 10013L
        val COLLISION_ACHIEVEMENT_CREATE_FANDOM_CHAT = 10014L
        val COLLISION_ACHIEVEMENT_REVIEW_MODER_ACTION = 10015L
        val COLLISION_ACHIEVEMENT_ACCEPT_FANDOM = 10016L
        val COLLISION_ACHIEVEMENT_CHAT_SUBSCRIBE = 10017L
        val COLLISION_ACHIEVEMENT_RATE = 10017L
        val COLLISION_ACHIEVEMENT_CHAT = 10018L
        val COLLISION_ACHIEVEMENT_RELAY_RACE_FIRST_POST = 10019L
        val COLLISION_ACHIEVEMENT_RELAY_RACE_FIRST_NEXT_MEMBER = 10020L
        val COLLISION_ACHIEVEMENT_RELAY_RACE_FIRST_CREATE = 10021L
        val COLLISION_ACHIEVEMENT_RELAY_RACE_POSTS_COUNT = 10022L
        val COLLISION_ACHIEVEMENT_RELAY_RACE_MY_RACE_POSTS_COUNT = 10023L
        val COLLISION_ACHIEVEMENT_VICEROY_ASSIGN = 10024L
        val COLLISION_ACHIEVEMENT_VICEROY_LINK = 10025L
        val COLLISION_ACHIEVEMENT_VICEROY_IMAGES = 10026L
        val COLLISION_ACHIEVEMENT_VICEROY_DESCRIPTIONS = 10027L
        val COLLISION_FANDOM_SUBSCRIBE = 20L
        val COLLISION_FANDOM_DESCRIPTION = 20000L
        val COLLISION_FANDOM_GALLERY = 20001L
        val COLLISION_FANDOM_LINK = 20002L
        val COLLISION_FANDOM_NOTIFY_IMPORTANT = 20003L
        val COLLISION_FANDOM_TITLE_IMAGE = 20004L
        val COLLISION_FANDOM_NAMES = 20005L
        val COLLISION_CHAT_BACKGROUND_IMAGE = 20012L
        val COLLISION_FANDOM_PINNED_POST = 20013L
        val COLLISION_FANDOM_VICEROY = 20014L
        val COLLISION_FANDOM_PARAMS_4 = 20015L
        val COLLISION_FANDOM_PARAMS_1 = 20016L
        val COLLISION_FANDOM_PARAMS_2 = 20017L
        val COLLISION_FANDOM_PARAMS_3 = 20018L
        val COLLISION_FANDOM_SUGGESTION_NOTES = 20019L
        val COLLISION_ACCOUNT_FOLLOW = 8L
        val COLLISION_ACCOUNT_QUEST = 17L
        val COLLISION_ACCOUNT_NOTIFICATION_TOKEN = 23L
        val COLLISION_ACCOUNT_STATUS = 30002L
        val COLLISION_ACCOUNT_AGE = 30003L
        val COLLISION_ACCOUNT_DESCRIPTION = 30004L
        val COLLISION_ACCOUNT_LINKS = 30005L
        val COLLISION_ACCOUNT_BLACK_LIST_ACCOUNT = 30006L
        val COLLISION_ACCOUNT_FOLLOW_NOTIFY = 30007L
        val COLLISION_ACCOUNT_REPORT = 30008L
        val COLLISION_ACCOUNT_NOTE = 30009L
        val COLLISION_ACCOUNT_COMMENTS_COUNT = 30010L
        val COLLISION_ACCOUNT_POSTS_COUNT = 30011L
        val COLLISION_ACCOUNT_COMMENTS_KARMA = 30012L
        val COLLISION_ACCOUNT_POSTS_KARMA = 30013L
        val COLLISION_ACCOUNT_UP_RATES = 30014L
        val COLLISION_ACCOUNT_UP_OVER_DOWN_RATES = 30015L
        val COLLISION_ACCOUNT_KARMA_COUNT = 30016L
        val COLLISION_ACCOUNT_LAST_DAILY_ENTER_DATE = 30017L
        val COLLISION_ACCOUNT_DAILY_ENTERS_COUNT = 30018L
        val COLLISION_ACCOUNT_MODERATION_KARMA = 30019L
        val COLLISION_ACCOUNT_PINNED_POST = 30020L
        val COLLISION_ACCOUNT_STICKERS_KARMA = 30021L
        val COLLISION_ACCOUNT_BLACK_LIST_FANDOM = 30022L
        val COLLISION_ACCOUNT_STICKERPACKS = 30023L
        val COLLISION_ACCOUNT_STICKERS = 30024L
        val COLLISION_ACCOUNT_PROJECT_INIT = 30025L
        val COLLISION_PROJECT_AB_PARAMS = 40000L
        val COLLISION_PROJECT_KEY = 40001L
        val COLLISION_PROJECT_MINIGAME_HUMANS = 40002L
        val COLLISION_PROJECT_MINIGAME_ROBOTS = 40003L
        val COLLISION_PROJECT_API_INFO = 40004L
        val COLLISION_PUBLICATION_REPORT = 7L
        val COLLISION_PUBLICATION_REACTION = 50000L
        val COLLISION_RUBRICS_NOTIFICATIONS = 60000L

        val REPORT_COMMENT_L = 500

        val COMMENT_MIN_L = 1
        val COMMENT_MAX_L = 1000

        val CHAT_TYPE_FANDOM_ROOT = 1L
        val CHAT_TYPE_PRIVATE = 2L
        val CHAT_TYPE_CONFERENCE = 3L
        val CHAT_TYPE_FANDOM_SUB = 4L
        val CHAT_MESSAGE_TEXT_MAX_L = 2000
        val CHAT_MESSAGE_TEXT_MIN_L = 1
        val CHAT_MESSAGE_IMAGE_WEIGHT = 1024 * 64
        val CHAT_MESSAGE_IMAGE_SIDE = 1000
        val CHAT_MESSAGE_IMAGE_SIDE_GIF = 400
        val CHAT_MESSAGE_GIF_MAX_WEIGHT = 1024 * 1024
        val CHAT_MESSAGE_MAX_IMAGES_COUNT = 5
        val CHAT_MESSAGE_VOICE_MAX_MS = 20000L
        val CHAT_MESSAGE_QUOTE_MAX_SIZE = 300
        val CHAT_MEMBER_STATUS_DELETE = 0L
        val CHAT_MEMBER_STATUS_ACTIVE = 1L
        val CHAT_MEMBER_STATUS_LEAVE = 2L
        val CHAT_MEMBER_STATUS_DELETE_AND_LEAVE = 3L
        val CHAT_MEMBER_LVL_USER = 1L
        val CHAT_MEMBER_LVL_MODERATOR = 2L
        val CHAT_MEMBER_LVL_ADMIN = 3L

        val TAG_NAME_MIN_L = 1
        val TAG_NAME_MAX_L = 20
        val TAG_IMAGE_SIDE = 64
        val TAG_IMAGE_WEIGHT = 1024 * 2

        val STICKERS_PACK_IMAGE_SIDE = 256
        val STICKERS_PACK_IMAGE_WEIGHT = 1024 * 16
        val STICKERS_PACK_NAME_L_MIN = 2
        val STICKERS_PACK_NAME_L_MAX = 100
        val STICKERS_IMAGE_SIDE = 300
        val STICKERS_IMAGE_SIDE_GIF = 300
        val STICKERS_IMAGE_WEIGHT = 1024 * 8
        val STICKERS_IMAGE_WEIGHT_GIF = 1024 * 64
        val STICKERS_MAX_COUNT_IN_PACK = 50
        val STICKERS_PACK_MAX_COUNT_ON_ACCOUNT = 50
        val STICKERS_MAX_COUNT_ON_ACCOUNT = 100

        val HISTORY_PUBLICATION_TYPE_UNKNOWN = 1L
        val HISTORY_PUBLICATION_TYPE_CREATED = 2L
        val HISTORY_PUBLICATION_TYPE_ADMIN_BACK_DRAFT = 3L
        val HISTORY_PUBLICATION_TYPE_ADMIN_BLOCK = 4L
        val HISTORY_PUBLICATION_TYPE_ADMIN_CHANGE_FANDOM = 5L
        val HISTORY_PUBLICATION_TYPE_ADMIN_CLEAR_REPORTS = 6L
        val HISTORY_PUBLICATION_TYPE_ADMIN_DEEP_BLOCK = 7L
        val HISTORY_PUBLICATION_TYPE_ADMIN_NOT_BLOCK = 8L
        val HISTORY_PUBLICATION_TYPE_ADMIN_NOT_MULTILINGUAL = 9L
        val HISTORY_PUBLICATION_TYPE_BACK_DRAFT = 10L
        val HISTORY_PUBLICATION_TYPE_CHANGE_FANDOM = 11L
        val HISTORY_PUBLICATION_TYPE_EDIT_PUBLIC = 12L
        val HISTORY_PUBLICATION_TYPE_MULTILINGUAL = 13L
        val HISTORY_PUBLICATION_TYPE_NOT_MULTILINGUAL = 14L
        val HISTORY_PUBLICATION_TYPE_PUBLISH = 15L
        val HISTORY_PUBLICATION_TYPE_ADMIN_CHANGE_TAGS = 16L
        val HISTORY_PUBLICATION_TYPE_ADMIN_IMPORTANT = 17L
        val HISTORY_PUBLICATION_TYPE_ADMIN_NOT_IMPORTANT = 18L
        val HISTORY_PUBLICATION_TYPE_ADMIN_PIN_FANDOM = 19L
        val HISTORY_PUBLICATION_TYPE_ADMIN_UNPIN_FANDOM = 20L
        val HISTORY_PUBLICATION_TYPE_CHANGE_TAGS = 21L
        val HISTORY_PUBLICATION_TYPE_PIN_PROFILE = 22L
        val HISTORY_PUBLICATION_TYPE_UNPIN_PROFILE = 23L
        val HISTORY_PUBLICATION_TYPE_ADMIN_NOT_DEEP_BLOCK = 24L
        val HISTORY_PUBLICATION_TYPE_CLOSE = 25L
        val HISTORY_PUBLICATION_TYPE_ADMIN_CLOSE = 26L
        val HISTORY_PUBLICATION_TYPE_CLOSE_NO = 27L
        val HISTORY_PUBLICATION_TYPE_ADMIN_CLOSE_NO = 28L
        val HISTORY_PUBLICATION_TYPE_ADMIN_REMOVE_MEDIA = 29L

        //
        //  Post
        //


        val PAGE_TEXT_MAX_L = 50000
        val PAGE_TEXT_TITLE_MAX_L = 100
        val PAGE_IMAGE_SIDE = 1500
        val PAGE_IMAGE_SIDE_GIF = 400
        val PAGE_IMAGE_WEIGHT = 1024 * 128
        val PAGE_IMAGE_GIF_WEIGHT = 1024 * 1024 * 6
        val PAGE_VIDEO_IMAGE_SIDE = 1000
        val PAGE_VIDEO_IMAGE_WEIGHT = 1024 * 64
        val PAGE_QUOTE_AUTHOR_MAX_L = 50
        val PAGE_QUOTE_TEXT_MAX_L = 1000
        val PAGE_LINK_NAME_MAX_L = 100
        val PAGE_LINK_WEB_MAX_L = 500
        val PAGE_LINK_SPOILER_MAX = 10
        val PAGE_LINK_SPOILER_NAME_MAX_L = 100
        val PAGE_POLLING_OPTION_MAX_TEXT = 200
        val PAGE_POLLING_OPTION_MAX_COUNT = 10
        val PAGE_POLLING_TITLE_MAX = 100
        val PAGE_POLLING_BLACKLIST_MAX = 10
        val PAGE_IMAGES_MINI_SIDE = 500
        val PAGE_IMAGES_MINI_WEIGHT = 1024 * 16
        val PAGE_IMAGES_SIDE = 1980
        val PAGE_IMAGES_WEIGHT = 1024 * 128
        val PAGE_IMAGES_SIDE_GIF = 164
        val PAGE_IMAGES_WEIGHT_GIF = 1024 * 512
        val PAGE_IMAGES_MAX_COUNT = 10
        val PAGE_IMAGES_TITLE_MAX = 100
        val PAGE_TABLE_MAX_COLUMNS = 5
        val PAGE_TABLE_TITLE_MAX = 100
        val PAGE_TABLE_MAX_ROWS = 30
        val PAGE_TABLE_MAX_TEXT_SIZE = 1000
        val PAGE_TABLE_MAX_IMAGE_SIDE = 512
        val PAGE_TABLE_MAX_IMAGE_SIDE_GIF = 128
        val PAGE_TABLE_MAX_IMAGE_WEIGHT = 1024 * 512
        val PAGE_TABLE_MAX_IMAGE_WEIGHT_GIF = 1024 * 1024
        val PAGE_DOWNLOAD_TITLE_MAX = 100
        val PAGE_DOWNLOAD_SIZE_MAX = 1024 * 1024 * 50
        val PAGE_CAMPFIRE_OBJECT_LINK_MAX = 2000
        val PAGE_LINK_IMAGE_W = 800
        val PAGE_LINK_IMAGE_H = 400
        val PAGE_LINK_IMAGE_WEIGHT = 1024 * 128

        val PAGES_SOURCE_TYPE_POST = 1L
        val PAGES_SOURCE_TYPE_WIKI = 2L

        val POST_MAX_PAGES_COUNT = 100

        //
        //  Notifications
        //

        val NOTIF_KARMA_ADD = 1L
        val NOTIF_COMMENT = 2L
        val NOTIF_COMMENT_ANSWER = 3L
        val NOTIF_ACCOUNT_FOLLOWS_ADD = 4L
        val NOTIF_ACHI = 7L
        val NOTIF_CHAT_MESSAGE = 8L
        val NOTIF_CHAT_MESSAGE_ANSWER = 9L
        val NOTIF_FOLLOWS_PUBLICATION = 10L
        val NOTIF_CHAT_MESSAGE_CHANGE = 11L
        val NOTIF_PUBLICATION_BLOCK = 12L
        val NOTIF_CHAT_MESSAGE_REMOVE = 13L
        val NOTIF_CHAT_TYPING = 14L
        val NOTIF_FANDOM_ACCPTED = 15L
        val NOTIF_QUEST_POGRESS = 18L
        val NOTIF_PUBLICATION_IMPORTANT = 19L
        val NOTIF_MODERATION_TO_DRAFTS = 20L
        val NOTIF_PROJECT_AB_PARAMS_CHAGED = 21L
        val NOTIF_MODERATION_POST_TAGS = 22L
        val NOTIF_MODERATION_FORGIVE = 23L
        val NOTIF_CHAT_READ = 24L
        val NOTIF_BLOCK = 25L
        val NOTIF_FANDOM_MAKE_MODERATOR = 26L
        val NOTIF_FANDOM_REMOVE_MODERATOR = 27L
        val NOTIF_PUNISHMENT_REMOVE = 28L
        val NOTIF_PUBLICATION_RESTORE = 29L
        val NOTIF_MODERATION_REJECTED = 30L
        val NOTIF_ADMIN_STATUS_REMOVE = 31L
        val NOTIF_ADMIN_DESCRIPTION_REMOVE = 32L
        val NOTIF_ADMIN_NAME_REMOVE = 33L
        val NOTIF_ADMIN_LINK_REMOVE = 34L
        val NOTIF_ADMIN_POST_FANDOM_CHANGE = 35L
        val NOTIF_PUBLICATION_BLOCK_AFTER_REPORT = 36L
        val NOTIF_MENTION = 37L
        val NOTIF_UNKNOWN = 38L
        val NOTIF_MODERATION_MULTILINGUAL_NOT = 39L
        val NOTIF_QUEST_FINISH = 40L
        val NOTIF_MODERATION_POST_CLOSE = 41L
        val NOTIF_MODERATION_POST_CLOSE_NO = 42L
        val NOTIF_RUBRICS_CHANGE_NAME = 43L
        val NOTIF_RUBRICS_CHANGE_OWNER = 44L
        val NOTIF_RUBRICS_MAKE_OWNER = 45L
        val NOTIF_RUBRICS_REMOVE = 46L
        val NOTIF_RUBRICS_KARMA_COF_CHANGED = 47L
        val NOTIF_RUBRICS_MOVE_FANDOM = 65L
        val NOTIF_PUBLICATION_REACTION = 48L
        val NOTIF_ACTIVITIES_RELAY_RACE_TURN = 49L
        val NOTIF_ACTIVITIES_RELAY_RACE_LOST = 50L
        val NOTIF_ACTIVITIES_NEW_POST = 51L
        val NOTIF_ACTIVITIES_RELAY_RACE_REJECTED = 52L
        val NOTIF_FANDOM_VICEROY_ASSIGN = 53L
        val NOTIF_FANDOM_VICEROY_REMOVE = 54L
        val NOTIF_ALIVE = 55L
        val NOTIF_DONATE = 56L
        val NOTIF_EFFECT_ADD = 57L
        val NOTIF_EFFECT_REMOVE = 58L
        val NOTIF_TRANSLATE_ACCEPTED = 59L
        val NOTIF_TRANSLATE_REJECTED = 60L
        val NOTIF_ADMIN_POST_MEDIA_REMOVE = 61L
        val NOTIF_FANDOM_REMOVE_CANCEL = 62L
        val NOTIF_ACCOUNT_ADMIN_VOTE_CANCELED_FOR_ADMIN = 63L
        val NOTIF_ACCOUNT_ADMIN_VOTE_CANCELED_FOR_USER = 64L

        val SUBSCRIPTION_NOTIF = 1L

        val REACTIONS = arrayOf(
                API_RESOURCES.EMOJI_1,
                API_RESOURCES.EMOJI_2,
                API_RESOURCES.EMOJI_3,
                API_RESOURCES.EMOJI_4,
                API_RESOURCES.EMOJI_5,
                API_RESOURCES.EMOJI_6,
                API_RESOURCES.EMOJI_7
        )
        //
        //  Language
        //

        val LANGUAGES: ArrayList<Language> = ArrayList()

        val LANGUAGE_EN = 1L
        val LANGUAGE_RU = 2L
        val LANGUAGE_PT = 3L
        val LANGUAGE_UK = 4L
        val LANGUAGE_DE = 5L
        val LANGUAGE_IT = 6L
        val LANGUAGE_PL = 7L
        val LANGUAGE_FR = 8L

        init {
            LANGUAGES.add(Language(LANGUAGE_EN, "English", "en"))
            LANGUAGES.add(Language(LANGUAGE_RU, "Русский", "ru"))
            LANGUAGES.add(Language(LANGUAGE_PT, "Portugues", "pt"))
            LANGUAGES.add(Language(LANGUAGE_UK, "Українська", "uk"))
            LANGUAGES.add(Language(LANGUAGE_DE, "Deutsch", "de"))
            LANGUAGES.add(Language(LANGUAGE_IT, "Italiano", "it"))
            LANGUAGES.add(Language(LANGUAGE_PL, "Polski", "pl"))
            LANGUAGES.add(Language(LANGUAGE_FR, "Français", "fr"))

            val list = LANGUAGES.sortedWith(compareBy { it.name })
            LANGUAGES.clear()
            for (i in list) LANGUAGES.add(i)
        }

        fun selector(p: Language): String = p.name

        fun getLanguage(code: String): Language {
            for (i in LANGUAGES) if (i.code == code.toLowerCase()) return i
            return LANGUAGES[0]
        }

        fun getLanguage(languageId: Long): Language {
            for (l in LANGUAGES) if (l.id == languageId) return l
            return LANGUAGES[0]
        }

        fun isLanguageExsit(languageId: Long): Boolean {
            for (l in LANGUAGES) if (l.id == languageId) return true
            return false
        }

    }


    override fun getApiVersion() = VERSION

}
